### ISSUE TITLE
适当减少diablo-client的外部依赖，保持client的轻量

### ISSUE THREAD

**Issue by qinerg** [ihaolin/diablo#4]
目前diablo-client依赖了8个jar的相关库。
diablo-common-1.1.1.jar
common-1.1.2.jar
http-request-6.0.jar
jackson-databind-2.4.2.jar
jackson-annotations-2.4.0.jar
jackson-core-2.4.2.jar
guava-19.0.jar
slf4j-api-1.7.21.jar
虽然部分库很多程序都可能用到，如slf4j。但是否可以考虑减少diablo-client的相关依赖，保持client的引用体积，这样就更完美了，呵呵

**Comment by ihaolin** [comment]
个人对轻量的理解：不包含偏重的第三方组件，如网络，中间件等，而不是说包越少越轻量：
- common-1.1.2.jar：这些包含一些通用工具，HTTP，JSON，时间等，不用也不影响外部系统，以至于不能启动应用。
- guava-19.0.jar：现代JAVA应用必备；
- slf4j-api-1.7.21.jar 这个只是API，具体log实现，外部自己决定，log4j，logback，log4j2都可以；
- jackson*：JSON库，这里是强依赖；
- http-request：一个原生HTTP库，而没用apache-httpclient，这里是强依赖。
