### ISSUE TITLE
为什么不考虑集成zookeeper？

### ISSUE THREAD

**Issue by wty007** [ihaolin/diablo#5]

**Comment by ihaolin** [comment]
- 作为客户端不引入，是不希望使用方都依赖zk；
- 作为服务端不引入：
  - 存储不用zk，zk对的数据查询能力不足；
  - 集群管理不用zk，没有太多需要协调的操作，也没有十分需要实时的处理，故没有使用；
- 本着能少维护一套服务器就尽量少，尽管zk已经比较成熟。
