### ISSUE TITLE
是否有REST接口文档或其他语言客户端?

### ISSUE THREAD

**Issue by astwyg** [ihaolin/diablo#6]
麻烦更一下REST接口文档呗, 想试一下一下在js和python客户端下的使用情况.

多谢.

**Comment by ihaolin** [comment]
好的，稍后会更新，现在客户端只支持java，其他语言还待支持。

**Comment by ihaolin** [comment]
@astwyg 初步文档已定：[https://github.com/ihaolin/diablo/blob/master/CLIENT_API.md](https://github.com/ihaolin/diablo/blob/master/CLIENT_API.md)。
